### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by liamdalg** [BigMacintosh/Parking#102]
**What Do You Want?**
Should probably start testing our really ugly code, especially the server/client packets.

**How Do We Do It?**
Implement a `TestServer` and `TestClient` (or equivalent) which just send a bunch of packets to each other.

**Comment by RileyEv** [comment]
We should probably have unit tests too on the packet serialising/deserialising

**Comment by RileyEv** [comment]
We might want to do this

**Comment by RileyEv** [comment]
I'll start to have a look at this shit

**Comment by ChrisGora** [comment]
I had a quick look (see branch `UTF-is-shit`). In summary, we might be able to write some tests, but I had a ton of errors that it didn't see any of the Networking classes when running any tests and I stopped there.

**Comment by RileyEv** [comment]
might be a stupid question but why `UTF`?

> I had a quick look (see branch `UTF-is-shit`). In summary, we might be able to write some tests, but I had a ton of errors that it didn't see any of the Networking classes when running any tests and I stopped there.

**Comment by RileyEv** [comment]
My plan was to have a look tomorrow at some test stuff

**Comment by ChrisGora** [comment]
Unity Testing Framework

**Comment by RileyEv** [comment]
I managed to get the tests working, you have to run them in unity though, rider doesn't seem to work for me

**Comment by ChrisGora** [comment]
I'll try to write a real test for the `RoundManager`. On another note, should we be commiting stuff in the packages folder? I was adding to the `.gitignore` cos I don't think that stuff needs to be on the repo.

**Comment by RileyEv** [comment]
they don't seem to be included in this https://github.com/github/gitignore/blob/master/Unity.gitignore

so I'm inclined to keep them

**Comment by RileyEv** [comment]
If we are getting rid of them then surely it would be best to hide the whole folder rather than individual things in the folder

**Comment by ChrisGora** [comment]
Split into #251 and #252
