### ISSUE TITLE
Investigate ways to actually start a game on the server

### ISSUE THREAD

**Issue by ChrisGora** [BigMacintosh/Parking#119]
**What Do You Want?**
On the day we should be able to:
- Start a new game using the server
- Stop an ongoing game

**How Do We Do It?**
1. `stdin` on the SSH connection to the server: Can we even read from `stdin`?
2. A Unity-based spectator-mode build that we use to control the server. 
3. A Python (or another lang) based client that sends UDP commands to the server.
4. ???

**Comment by RileyEv** [comment]
> A Python (or another lang) based client that sends UDP commands to the server.

I can try and implement some packets on the server and then use Wireshark to observe how unity sends them to create a python script, but this seems bit silly. 


> A Unity-based spectator-mode build that we use to control the server.

We could create an option on the menu when you first start it up and it opens up a menu, which we can use. This avoids needing a new build
