### ISSUE TITLE
End of round countdown timer

### ISSUE THREAD

**Issue by RileyEv** [BigMacintosh/Parking#123]
**What Do You Want?**
A countdown at the end of the round

**How Do We Do It?**
Packet from server to inform clients of the start of the countdown

**Comment by RileyEv** [comment]
For now we can just countdown for the length of the whole round

**Comment by RileyEv** [comment]
Timer class has been extended so that you can have it trigger at set intervals.

**Comment by Dimmitsaras** [comment]
Done as a client-side thing for now
