### ISSUE TITLE
Use properties

### ISSUE THREAD

**Issue by ChrisGora** [BigMacintosh/Parking#151]
We've used properties with a getter/setter, then wrapped them with an explicit setter. We can just have the property implement this behaviour, e.g.

```C#
private int occupiedBy;
public int OccupiedBy 
{
    get 
    { 
        return occupiedBy; 
    }
    set 
    {
        mat.color = new Color(0, 1, 0, 0.3f);
        occupiedBy = value;
    }
}
```

_Originally posted by @liamdalg in https://github.com/BigMacintosh/Parking/pull/150_

**Comment by liamdalg** [comment]
You might be able to do

```C#
get => occupiedBy;
```

to save those precious lines :eyes:

**Comment by liamdalg** [comment]
After looking at it further, if you don't want a property to have a side-effect (which is also sensible but I don't care either way), I would change the property to:

```C#
public int OccupiedBy { get; private set; }
```

and just leave the method as-is.
