### ISSUE TITLE
Load server network configuration from files

### ISSUE THREAD

**Issue by liamdalg** [BigMacintosh/Parking#17]
Implement some sort of config that we can load the ip/port from (and possibly other stuff as we go along).

**Comment by RileyEv** [comment]
arghh were both doing this at the same time... 😂

**Comment by RileyEv** [comment]
don't we need to do this for server and client or will client be manual input(in game)

**Comment by ghost** [comment]
> don't we need to do this for server and client or will client be manual input?

More important for server I guess since it's easier to change just change the literal and recompile on client, whereas that is a tonne of effort on server.

**Comment by liamdalg** [comment]
Yeah think it'd be better to have manual input for client, eventually in an in game menu
