### ISSUE TITLE
Parking Space timers not cancelling at the end of the round.

### ISSUE THREAD

**Issue by liamdalg** [BigMacintosh/Parking#178]
**Describe the bug**
![Screen Shot 2020-02-26 at 17 56 17](https://user-images.githubusercontent.com/32525406/75373344-0a6c7080-58c2-11ea-954a-31ec3748d5e6.png)

- Player 1 entered player 0's space when there was less than three seconds remaining in round 0.
- Player 1 was disconnected (as expected).
- Player 1 then claimed the space after the PreRoundEvent for round 1. Therefore had claimed the space in round 1.
- Player 0 then did not claim a space in the next round.
- Player 0 did not get disconnected at the end of the round. Assuming it is to do with the fact that Player 1 had claimed a space but was no longer in the game. 

**Expected behavior**
- Player 1 should not have claimed the space. 
- Player 0 should have been eliminated in round 1.

**Comment by ChrisGora** [comment]
When a player enters a space just before the round ends they will end up claiming a space during the preRound of the next round, because the server timer is not cancelled
