### ISSUE TITLE
Need to end the game in some way

### ISSUE THREAD

**Issue by RileyEv** [BigMacintosh/Parking#182]
**What Do You Want?**
We need logic to end a game.

- Do we go for a fixed number of rounds/ till 1 player is left?
- What happens if no one gets a space in a round? Does the game end with no winners or do we have joint winners?

**Comment by ChrisGora** [comment]
Fixed number of rounds or until 1 player (whichever is shorter) sounds good.
The `GameEnd` event should probably contain a list of winners.

**Comment by ChrisGora** [comment]
Or does that only get sent to winners, because we disconnect the losers...?
