### ISSUE TITLE
Discuss plan for map and what we want it to look like

### ISSUE THREAD

**Issue by RileyEv** [BigMacintosh/Parking#21]

**Comment by adeeg** [comment]
![image](https://user-images.githubusercontent.com/3707470/68685160-98198f80-0561-11ea-8f73-337f19fa46e1.png)
fortnite

**Comment by adeeg** [comment]
![map](https://user-images.githubusercontent.com/3707470/69731286-8c14fc80-1121-11ea-8caf-2fde4ab88945.png)

**Comment by adeeg** [comment]
Idea is 4 main areas populated with more stuff/denser.

Smaller landmarks will be spread out in the more open areas.

Parking spaces will typically be next to landmarks but some will be hidden.
