### ISSUE TITLE
IsEliminated in the Player class is never set to true

### ISSUE THREAD

**Issue by ChrisGora** [BigMacintosh/Parking#227]
There doesn't seem to be any incorrect behaviour because of this. But that attribute either needs to be deleted or correctly set somewhere.

**Comment by RileyEv** [comment]
Yes this isn’t set up yet. It was going to be done when we’re ready to have police cars. It’s been added so it’s there ready. But the police car logic isn’t there

**Comment by RileyEv** [comment]
There’s several things in the world there to be ready for the future, but aren’t used yet

**Comment by ChrisGora** [comment]
Alright... In the future I don't think that kind of stuff should make it to master

**Comment by RileyEv** [comment]
I think it should, if you develop a library for someone else to use then there will at point be things that aren’t used. Until someone uses them. If we don’t commit things like that then it makes working independently very difficult. As I’ll have something on a branch that we can’t merge into master but you’ll want to develop something with it. Then it starts to cause very messy merges.

Something being unused on master is not a bad thing. It’s only bad if it will never be used or is causing bugs.
