### ISSUE TITLE
Tweak road tool raycasting

### ISSUE THREAD

**Issue by ChrisGora** [BigMacintosh/Parking#234]
Might be worth looking at:
- Also raycasting the middle point.
- Setup raycast layers so the only thing collided with is the terrain.

**Comment by Keywarn** [comment]
I think raycasting with the middle is good. As for it being 'level' having it perfectly level isn't very viable as the engine struggles with which faces to draw over the other. 

A lot of the issues we are having stem from the way the car is designed. I think if we change it to raycast in the middle (to prevent terrain going through) then improve the car/make it more stable it should be able to get up onto the road more easily.
