### ISSUE TITLE
Fix HUD

### ISSUE THREAD

**Issue by RileyEv** [BigMacintosh/Parking#26]
@Dimmitsaras I think I fucked up copying your head up display with speed when merging your branch. Not quite sure how to add it back. Could you have a look please? 🙏

**Comment by Dimmitsaras** [comment]
I believe it should be fixed, put it on a new branch so we can check before merging. I'm having trouble launching the master branch due to network references and stuff, but it worked on my local version. Basically the scene needs a text object that uses the HUD script to display the text.

**Comment by RileyEv** [comment]
Cheers :). To fix the network stuff the best thing to do is delete the whole folder with the repo and just clone it again. The submodules got bit weird and brake unless you reclone.
