### ISSUE TITLE
Design level

### ISSUE THREAD

**Issue by adeeg** [BigMacintosh/Parking#3]
see title

**Comment by adeeg** [comment]
could use real life data for hills

**Comment by adeeg** [comment]
ideas

* inset road
* roundabout
* slight incline
* hill + valley
* ramps
* tubes + loop de loop
* underground
* collision objs/playground area

**Comment by Keywarn** [comment]
Adam's Airdropped design:
![design](https://user-images.githubusercontent.com/43956629/67381875-80fc0900-f584-11e9-8749-606971d02140.png)

**Comment by RileyEv** [comment]
@Nenivar Assume that this is done now so should I close the issue?

**Comment by adeeg** [comment]
yes
