### ISSUE TITLE
Wheel Collider-less Driving

### ISSUE THREAD

**Issue by Keywarn** [BigMacintosh/Parking#59]
Start experimenting with a rigid-body approach to the driving and ditch those bloody wheel colliders once and for all. There are plenty of tutorials online to help us choose the kind of mechanics we want.

**Comment by RileyEv** [comment]
This one uses wheel colliders but seems to look natural https://www.youtube.com/watch?v=j6_SMdWeGFI

**Comment by Keywarn** [comment]
> This one uses wheel colliders but seems to look natural https://www.youtube.com/watch?v=j6_SMdWeGFI

I did originally try following that video but I had very different results. The problem is that the physics are affected by things like the model size which will be different for different vehicles etc.

**Comment by Keywarn** [comment]
Although everything I am finding now which is relevant or recent seems to be done with wheel colliders. Maybe it's worth just starting from scratch tweaking it properly.

That being said, I suspect if want to go for a more 'mario kart' feel then we might be better of writing a more 'naive' handler.
