### ISSUE TITLE
Implement network packets needed for round manager

### ISSUE THREAD

**Issue by RileyEv** [BigMacintosh/Parking#70]
Packets to be implemented are:

- [x] Round Start: Server -> Client
- [x] Pre Round Start: Server -> Client
- [x] Round End: Server -> Client
- [x] Space: Client -> Server (in response to Round End)
- [x] Eliminate Players: Server -> Client

Data to be transferred each packet currently is as follows:
**Pre Round Start**:
- round number(byte)
- pre round length(byte, should only be up to 255s)
- round length(byte, hopefully a round isn’t longer than 255 secs)
- number of players(byte), 
- spaces activated(list of bytes).

**Round Start**:
- round number(byte).

**Round End**:
- round number(byte).

**Space**: 
- round number(byte)
- spaceID(byte, im assuming no more than 255 unique spaces on the map, including the ones that aren’t active).

**Eliminate Players**:
- round number(byte)
- players eliminated (list of player ids). Whatever data type we use to store player IDs in the world/server. I can’t remember what that is.

_Originally posted by @RileyEv in https://github.com/BigMacintosh/Parking/issues/64#issuecomment-579312981_

**Comment by ghost** [comment]
> Whatever data type we use to store player IDs in the world/server. I can’t remember what that is.

byte for networking player ids
