### ISSUE TITLE
ClientHandshakeEvent should reject connections when a game is in progress

### ISSUE THREAD

**Issue by RileyEv** [BigMacintosh/Parking#76]
When `RoundManager` triggers `StartGameEvent` if the server receives a `ClientHandshakeEvent` then the server should send a packet back stating that the connection has been refused.

When the `GameOverEvent` is triggered the server will go back to accepting new connections.

**Comment by RileyEv** [comment]
@ChrisGora Did this get merged on Friday or is it on your current parking branch?

**Comment by ChrisGora** [comment]
I don't think I've done this...?

**Comment by RileyEv** [comment]
I thought you'd made it so that players can't connect when a game is in progress?

**Comment by ChrisGora** [comment]
Oooh yeah I've done something like that... But on the round manager branch

**Comment by RileyEv** [comment]
Okay will close this then
