### ISSUE TITLE
Combine ServerRoundStartEvent and ServerRoundEndEvent

### ISSUE THREAD

**Issue by RileyEv** [BigMacintosh/Parking#80]
**What Do You Want?**
Merge the two events into a single event as currently they are duplicates of each other, just with different names.

**How Do We Do It?**
Create a single packet which also now includes a boolean to indicate if it is for start or end

**Comment by ghost** [comment]
Should we actually do this? I feel like packet IDs are not in short supply and I mean technically it does save us a byte or whatever. Tbh I don't mind either way but if we don't need to do the extra work...

**Comment by RileyEv** [comment]
At the moment we've literally got two classes that have exactly the same thing in them, just with a different class name. Sounds like the wrong thing to do. 

Maybe we could create an abstract packet and then just define both to inherit from it so we've got the distinction while coding and that would save the byte.

**Comment by liamdalg** [comment]
Although I agree it's weird to have two copies, we don't know whether the packets will change in the future. This seems a bit like premature optimisation, no?

**Comment by ghost** [comment]
> At the moment we've literally got two classes that have exactly the same thing in them, just with a different class name. Sounds like the wrong thing to do.
> 
> Maybe we could create an abstract packet and then just define both to inherit from it so we've got the distinction while coding and that would save the byte.

I can get behind this, can we make Event just do this as the behaviour of an event with purely an ID is behaviour in common with all events? I think it's already close to doing this, it just lacks the correct Length of 1 being set?
