### ISSUE TITLE
Refactor HUD class to fit into game loop

### ISSUE THREAD

**Issue by RileyEv** [BigMacintosh/Parking#82]
**What Do You Want?**
HUD class needs refactoring so that the HUD is created within the `ClientGameLoop`. 

Can then listen for events from `Client` and display messages about the round.

**Comment by RileyEv** [comment]
@Dimmitsaras I've just noticed the stuff you pushed on `menu-stuff` seems to be a long way behind master. You're gonna need to try and move it to the latest version, or I fear we may get a big merge conflict.

https://github.com/BigMacintosh/Parking/compare/master...menu-stuff

**Comment by Dimmitsaras** [comment]
Will copy the stuff to a new build and re-push, got it.

**Comment by Dimmitsaras** [comment]
@RileyEv  I just pushed what works as monobehavior on the latest master version on menu-stuff-new (couldn't find a better way than make a new branch)

**Comment by RileyEv** [comment]
Cheers :smile: I'll have a look tonight and try and find the best way to integrate it into what we've got atm and walk you through it tomorrow, so you can try and move it all across.

**Comment by Dimmitsaras** [comment]
Okay, just note that it's dependent on the UICanvas object and I only added it for TestScene atm.
