### ISSUE TITLE
Exit button on escape menu should trigger Disconnect event on client

### ISSUE THREAD

**Issue by RileyEv** [BigMacintosh/Parking#98]
**What Do You Want?**
Before going to main menu the client should disconnect from the server.

**Comment by RileyEv** [comment]
Need to implement a disconnect event

**Comment by ChrisGora** [comment]
The disconnect event should be broadcasted to all the clients

**Comment by Dimmitsaras** [comment]
Currently calls Shutdown on clientgameloop via 

uiController.getHUD().exitbutton.onClick.AddListener(Shutdown);
