### ISSUE TITLE
Update ClientGameSettings with inputs from main menu

### ISSUE THREAD

**Issue by RileyEv** [BigMacintosh/Parking#99]
Requires #95 
**What Do You Want?**
When player enters details they should be stored 

**How Do We Do It?**
Use OnEditEnd event of text fields to store in ClientGameSettings.

**Comment by ChrisGora** [comment]
As discussed on Tuesday: The Car and Colour selection should also be stored.

**Comment by RileyEv** [comment]
Completed for names and server ip

**Comment by liamdalg** [comment]
Might be nice if we made the menu show the current value as a placeholder in the server ip field?
